ALTER TABLE usuario ADD COLUMN valorPresencial VARCHAR(50) NULL;
ALTER TABLE usuario ADD COLUMN valorOnline VARCHAR(50) NULL;
ALTER TABLE usuario ADD COLUMN valorDomiciliar VARCHAR(50) NULL;
ALTER TABLE reservas ADD COLUMN modalidade VARCHAR(30) NULL;
ALTER TABLE reservas ADD COLUMN valor VARCHAR(50) NULL;
