ALTER TABLE reservas ADD COLUMN lembrete_presenca_48h TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE reservas ADD COLUMN lembrete_presenca_36h TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE reservas ADD COLUMN lembrete_presenca_24h TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE reservas ADD COLUMN lembrete_presenca_18h TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE reservas ADD COLUMN lembrete_presenca_16h TINYINT(1) NOT NULL DEFAULT 0;
