ALTER TABLE usuario ADD COLUMN IF NOT EXISTS descricao TEXT;
ALTER TABLE usuario ADD COLUMN IF NOT EXISTS tempoAtendimento VARCHAR(100);
ALTER TABLE usuario ADD COLUMN IF NOT EXISTS publicoAtendido VARCHAR(100);
ALTER TABLE usuario ADD COLUMN IF NOT EXISTS modalidade VARCHAR(100);
